mode: development
session_secret: 1b7e2d6e-b912-4664-a079-22522be0ea08
http_port: 4500
database: codelab

google_client_id: 961278028726-i4baurj84uri5q440vedq44bo8dpmi14.apps.googleusercontent.com
google_web_secret: vysKp687PqFSAU2YQtR0ia_T

subdomains:
  - www
  - billing
  - about
  - temp