mode: development
session_secret: 1b7e2d6e-b912-4664-a079-22522be0ea08
http_port: 4500
database: codelab

ssl_key: ~/../ssl/key
ssl_cert: ~/../ssl/cert
ssl_ca: ~/../ssl/ca

chargebee_api_key: test_H6s4r83e6wKuLHOq3GmDO7nSNeMMaCxc
chargebee_api_target: codelab-test

lesson_manifest: ~/lessons/
lesson_directory: ~/lessons/output/
audio_directory: ~/.audio/
cache_directory: ~/.cache/
data_directory: ~/.data/
audit_log: ~/.data/logs/audit.txt

azure_subscription_key: 5ec90588a27c47fba5bcec56b470c2a9

google_client_id: 961278028726-i4baurj84uri5q440vedq44bo8dpmi14.apps.googleusercontent.com
google_web_secret: vysKp687PqFSAU2YQtR0ia_T

subdomains:
  - www
  - billing
  - about
  - temp