monthly_cost: 125
phone_number: 972-861-0189
start_date: July 22nd

header_introduction: |
  We're helping young developers begin learning skills and best practices that will carry with them into their adult careers.


about_title: Start Learning Professional Skills Today
about_content: |
  Our goal at **CodeLab** is to start introducing teenagers to the same programming languages and tools used by professional software developers.

  **CodeLab** helps students get ahead by teaching them the same skills and best practices that will carry with them into their adult careers.

courses_title: Learn Real Coding Skills
courses_content: |
  **CodeLab** covers a wide variety of topics in order to introduce students to the same languages and technologies used by professional developers.


tutorials_title: Easy To Get Started
tutorials_content: |

  New students don't need to have prior experience before attending **CodeLab**.
  
  We use specially designed self-paced, interactive tutorials with an included **Teaching Assistant** to help a new student get up to speed quickly, even when they're away from class.
  
  After a student has finished all introductory lessons, they'll be ready to join in classroom lectures.


schedule_title: Schedule & Pricing
schedule_content: |
  **CodeLab** is self-paced, so we don't follow a strict schedule. Simply reserve a **60 minute session** on the date and time that works best for you and you're good to go!


reserve_title: Interested In Enrolling?
reserve_content: |
  **CodeLab** is opening soon, so if you'd like to be notified when enrollment begins, make sure to **reserve a space**!


faq_title: Frequently Asked Questions
faq_content: |
  Still have questions about **CodeLab**? Feel free to contact us with any remaining questions you have and we'll get back to you as soon as possible.


preEnroll: CodeLab sessions begin **July 22nd, 2019**. You will not be charged until that date.

enrollment_notes:
  - type: important
    message: |
      Enrollment for CodeLab **$125** which is **billed once per month**.
  
  - type: important
    message: |
      Each CodeLab session is one hour long, once per week, at the time you select.
  
  - message: |
      New students that are completing the self-paced tutorials may work on them from home.
  
  - message: |
      Students may access CodeLab from home to work on their own projects after requesting access.
  
  - message: |
      If a student is unable to attend a class, no make up options will be available. 
  
  - message: |
      Enrolling at CodeLab means that you are agreeing to the [CodeLab Policies](/policies).


plans:
  
  - title: At Home Plan
    cost: 30
    css: remote
    summary: Home access to weekly CodeLab tutorials and a Virtual Coach
    features:
      - icon: clock
        detail: Lessons completed from home

      - icon: coach
        detail: Access to Virtual Coach
      
      - icon: tools
        detail: Use CodeLab Tutorials from home

      - icon: share
        detail: Share creations online
      
      # - icon: discount
      #   detail: Discounts available

  - title: On-Site Plan
    cost: 125
    css: standard
    summary: On-site access to CodeLab with provided computers and a Code Coach
    features:
      - icon: clock
        detail: One 60 minute session per week

      - icon: coach
        detail: On-site Code Coach

      - icon: tools
        detail: Use all CodeLab features from home

      - icon: share
        detail: Share creations online
      
      # - icon: discount
      #   detail: Discounts available


faq:
  -
    question: What is the recommended age for CodeLab?
    answer: |
      Each student is different but we recommend that students be at least 10 years old before attending classes. **CodeLab** is intended to help young programmers to start learning the same technologies and best practices used by professional developers. 

      If you're unsure your learner is ready for **CodeLab**, let them try out the [self-paced example lesson online](/demo) to see if they're ready for the topics that we cover.

  -
    question: Why does CodeLab use self-paced tutorials?
    answer: |
      It's difficult to jump into something new, especially if you haven't had any prior experience with the topic at hand.

      At **CodeLab**, we've created self-paced tutorials that will help a new student become familiar with the basic concepts of the class so they're able to get familar with the course material without being overwhelmed.

  -
    question: Do we need to bring a laptop to attend classes?
    answer: |
      You can, if you'd like, but workstations will be available for use. If you would like to bring a your own device, it should have a keyboard, USB port, and headphone jack available.

      iPads are **not** recommended.

  -
    question: Can I see what my child is creating in class?
    answer: |
      Yes! We've discovered that being able to share work with friends and family is a great motivator for aspiring developers. Nearly every single lesson at **CodeLab** has a finished result can be shared with others when completed.

      You can also see the [Student Showcase](/showcase) to see some websites and apps created using CodeLab.

  -
    question: Do you teach programming with Minecraft or Scratch?
    answer: |
      We think that games like **Minecraft** and block based programming languages like **Scratch** are a fantastic way to get kids interested coding.

      However, our goal at **CodeLab** is to help students take their first steps into writing code with programming languages used by professional developers.
      
  -
    question: Can we use CodeLab in our school district?
    answer: |
      Yes! [Contact us](mailto://hello@codelabschool.com) for additional information about licensing **CodeLab** for use in your school district.



policies:
  
  - title: General Conditions
    summary: |
      We'll do our best to treat you and your information with respect.

    content: |
      We reserve the right to refuse service to anyone for any reason at any time.

      You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks.
      
      You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the service is provided, without express written permission by us.

      The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms.

  - title: Modification to the Service and Prices

    summary: |
      We might change prices at some point, but we'll do our best to notify you before that happens.

    content: |
      Prices for our products are subject to change without notice.

      We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time.

      We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service.

  - title: Third-Party Links

    summary: |
      CodeLab is not responsble for any websites that a Student creation might link to.

    content: |
      Certain content, products and services available via our Service may include materials from third-parties.

      Third-party links on this site may direct you to third-party websites that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third-parties.

      We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party's policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.

  - title: Comments, User Feedback
    summary: |
      CodeLab will not monitor comments posted on websites, apps, and games created.

      If you don't want to allow comments on Student created content, you may disable them entirely.

    content: |
      If, at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, 'comments'), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments.

      We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms of Service.

      You agree that your comments will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your comments will not contain libelous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead us or third-parties as to the origin of any comments. You are solely responsible for any comments you make and their accuracy. We take no responsibility and assume no liability for any comments posted by you or any third-party.

  - title: Prohibited Uses
    summary: |
      Don't use CodeLab to create websites or apps for illegal activities.

    content: |
      In addition to other prohibitions as set forth in the Terms of Service, you are prohibited from using the site or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.
  
  - title: Liability
    summary: |
      We'll do our best to make sure CodeLab is always online and available, but if it's not then we're not legally responsible.

      As unlikely as it may be, we're also stating that CodeLab is not responsible for injuries while learning programming _(including eye-strain or headaches)_

    content: |
      We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free.

      We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable.

      You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you.

      You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.

      In no case shall CodeLab, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.

  - title: Termination
    summary: |
      Both you or CodeLab may end working together at any time.

    content: |
      The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes.

      These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site.

      If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof).

  - title: Changes to Terms of Service

    summary: |
      Terms and conditions may change from time to time.

    content: |
      You can review the most current version of the Terms of Service at any time at this page.

      We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.

  
  - title: Intellectual Property and Student Creations
    summary: |
      Your student owns their creations and may to download them and keep them for themselves.
      
      We might ask to show off a students creations, but you're free to decline.


  - title: Session Make Up Policy
    summary: |
      You may try and find an open slot to take a make up session

      if not, the lesson can be enabled and completed from home

  - title: Refund Policy
    summary: |
      Refunds are available 

      Customer is responsible for any processing fees

  - title: Discounts
    summary: |
      Discounts are available

      Discounts may be discontinued at any time
