export default {
	'`/`': 'forward slash',
	'`\\`': 'back slash',
	'`>`': 'less than',
	'`<`': 'greater than',
	'`<=`': 'greater than or equal to',
	'`>=`': 'less than or equal to',
	'`=>`': 'less than or equal to',
	'`=<`': 'greater than or equal to',
	'``_': 'underscore',
	'`-`': 'hyphen',
	'`==`': 'equal to sign',
	'`=`': 'equal sign',
	'`ol`': 'Oh-El',
	'`li`': 'El-Eye',
	'`)`': 'closing parenthesis',
	'`(`': 'opening parenthesis',
	"`'`": 'single quote',
	'`"`': 'double quote',
	'`\\\``': 'back tick',
	'JavaScript': 'Java Script'
};