export default {
	'`/`': 'forward slash',
	'`\\`': 'back slash',
	'`>`': 'less than',
	'`<`': 'greater than',
	'`<=`': 'greater than or equal to',
	'`>=`': 'less than or equal to',
	'`=>`': 'less than or equal to',
	'`=<`': 'greater than or equal to',
	'`=`': 'equal sign',
	'`_`': 'underscore',
	'`-`': 'hyphen',
	'`==`': 'equal to sign',
	'`=`': 'equal sign',
	'`ol`': 'Oh-El',
	'`li`': 'El-Eye',
	'`)`': 'closing parenthesis',
	'`(`': 'opening parenthesis',
	"`'`": 'single quote',
	'`"`': 'double quote',
	'`br`': 'line break',
	'`p`': 'paragraph',
	'`h1`': 'heading one',
	'`img`': 'image',
	'`src`': 'source',
	'`a`': 'anchor',
	'`href`': 'h ref',
	'`\\\``': 'back tick',
	'JavaScript': 'Java Script'
};