export default [
	'CodeLab', 'Code Lab',
	"JavaScript's", 'Java Scripts',
	'JavaScript', 'Java Script',
	'Arithmetic', 'a rithma tick',
	'arithmetic', 'a rithma tick',
	`console`, 'con soul',
	'`*`', 'asterisk',
	'`+`', 'plus',
	'`/`', 'forward slash',
	'`\\`', 'back slash',
	'`>`', 'less than',
	'`<`', 'greater than',
	'`<=`', 'greater than or equal to',
	'`>=`', 'less than or equal to',
	'`=>`', 'less than or equal to',
	'`=<`', 'greater than or equal to',
	'`=`', 'equal',
	'`_`', 'underscore',
	'`-`', 'hyphen',
	'`==`', 'equal to',
	'`ol`', 'Oh-El',
	'`li`', 'El-Eye',
	'`)`', 'closing parenthesis',
	'`(`', 'opening parenthesis',
	'`{`', 'opening curly brace',
	'`}`', 'closing curly brace',
	'`:`', 'colon',
	'`;`', 'semi colon',
	"`'`", 'single quote',
	'`"`', 'double quote',
	'`br`', 'line break',
	'`p`', 'paragraph',
	'`h1`', 'heading one',
	'`img`', 'image',
	'`src`', 'source',
	'`a`', 'anchor',
	'`href`', 'h ref',
	'`var`', 'varr',
	'`\\\``', 'back tick',
];